In [66]:
import numpy as np
import pandas as pd

In [67]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [68]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [69]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [70]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 41.1 KB

In [71]:
# converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [72]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

# 1. Extract year,month,date,month_name

In [73]:
date['date_year']=date['date'].dt.year
date['date_month']=date['date'].dt.month
date['date_day']=date['date'].dt.day
date['date_month_name']=date['date'].dt.month_name()
date['date_dow']=date['date'].dt.dayofweek
date['date_dow_name']=date['date'].dt.day_name()
date['date_week'] = date['date'].dt.isocalendar().week
date['date_quarter']=date['date'].dt.quarter

In [74]:
date=date.drop(columns=['product_id','city_id','orders'])
date.head()

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_week,date_quarter
0,2019-12-10,2019,12,10,December,1,Tuesday,50,4
1,2018-08-15,2018,8,15,August,2,Wednesday,33,3
2,2018-10-23,2018,10,23,October,1,Tuesday,43,4
3,2019-08-17,2019,8,17,August,5,Saturday,33,3
4,2019-01-06,2019,1,6,January,6,Sunday,1,1

In [75]:
import datetime

today=datetime.datetime.today()

today

datetime.datetime(2026, 9, 29, 17, 31, 38, 58020)

In [76]:
today-date['date']

0     2485 days 17:31:38.058020
1     2967 days 17:31:38.058020
2     2898 days 17:31:38.058020
3     2600 days 17:31:38.058020
4     2823 days 17:31:38.058020
                 ...
995   2913 days 17:31:38.058020
996   2854 days 17:31:38.058020
997   2702 days 17:31:38.058020
998   2767 days 17:31:38.058020
999   2541 days 17:31:38.058020
Name: date, Length: 1000, dtype: timedelta64[us]

In [77]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [79]:
# converting to time datatype

time['date']=pd.to_datetime(time['date'])

In [80]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 100.1 KB

In [82]:
time['hour']=time['date'].dt.hour
time['minute']=time['date'].dt.minute
time['second']=time['date'].dt.second
time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [88]:
time['time']=time['date'].dt.time

In [89]:
time.head()

,date,msg,hour,minute,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [92]:
today-time['date']

0     4671 days 16:41:38.058020
1     4535 days 17:51:38.058020
2     5021 days 17:10:38.058020
3     4323 days 17:00:38.058020
4     4720 days 18:20:38.058020
                 ...
995   5310 days 16:41:38.058020
996   4631 days 18:17:38.058020
997   5096 days 17:54:38.058020
998   5212 days 17:57:38.058020
999   4484 days 18:06:38.058020
Name: date, Length: 1000, dtype: timedelta64[us]